### ISSUE TITLE
I could not  run the project

### ISSUE THREAD

**Issue by 93Kamuran** [twdes/odette#3]
Hello, I want to use your project for my customer is working with VW /Audi in Germany. they want to communicate with the oftp2 protocol. My customer has got Odette ID and certificate.  They told me that we send  application form to VW/Audi then they send an email to us  such as 
"    I have now set up a new station for you with the station identifier SID = PDC.
   Please make sure that your OFTP2 service is available and reports with a valid certificate.
   We are currently rejecting you   
  Opening connection to *.*.*.*:* 
       from *.*.*.*

java.net.ConnectException: Connection refused

 
"

 I Downloaded your project as zip file and tried to change some codes to run the app.  So  I could not run it.  Could you give some advice me, please?

**Comment by neolithos** [comment]
It looks like, that you have some problem with your tcp-connectionen?

Your are not provided enough information do resolve your problem.

First you should check your incoming connections.

**Comment by 93Kamuran** [comment]
I could run project on my test server. with your connection informations that you shared on the closed issue. However,
  - if I use this tag  "<http threads=1>"  ı see that message in console "threads is not defined"  . 
  - when I remove threads=1 on the http tag service runs.
  - btw  I always see on console this message like "@priority is not defined"  I forced the program with some code changes in "ConfigNode.cs"  234th line add one more else if there like name=="priority" return true;    

So   I run the project one way or another, but   on localhost ı see "[test] test: Konfiguration wurde erfolgreich geladen."  in test tab, 
![Capture](https://user-images.githubusercontent.com/43153928/71612876-3914e600-2bb4-11ea-90b0-adc701661c25.PNG)

- there is no session start  message on page. 

- When I  put  project to  my customer server I saw . "exception has been thrown by the target of an invocation" . 

error message on the command promt.

**Comment by neolithos** [comment]
Hello,

#### to "threads is not defined"
I removed this parameter, because with the async thread management it not necessary anymore.
Removing is correct.

#### to '@priority'
FileService's have a priority in the enumeration process, the warning can be ignored, or just add the a priority tag.

#### to "Konfiguration wurde erfolgreich geladen"
That means, the configuration could be parsed.

####  to 'session start message '
Session start is written to the log, if a connection was made sucessful.

#### to the exception
Please give me the full exception, you need to click the line.

May be, it will help if you can send me your configuration and the log folder.
You can send me your email over https://tecware-gmbh.de/kontakt.html.

**Comment by 93Kamuran** [comment]
I could not upload log file on this link I guess. Instead of this. I wrote an email to you.

**Comment by neolithos** [comment]
I send you an email

**Comment by 93Kamuran** [comment]
> I send you an email

I'm sorry there is not an email  I can see

**Comment by neolithos** [comment]
Your email was reject: "unknown user".

**Comment by 93Kamuran** [comment]
you can send it to kamuranengin@ideaktif.com or enginkamuran@gmail.com.   
I already send  you an email from kamuranengin@ideaktif.com

**Comment by neolithos** [comment]
And now...
